# Generated by Django 3.1 on 2020-09-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialData',
            new_name='HistoricalData',
        ),
    ]
