# Generated by Django 3.1 on 2020-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200908_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='priceinminutes',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
