# Generated by Django 3.1 on 2020-09-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200909_0638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.RemoveField(
            model_name='priceinminutes',
            name='market_price',
        ),
        migrations.AddField(
            model_name='priceinminutes',
            name='EUR',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='priceinminutes',
            name='GDP',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='priceinminutes',
            name='USD',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='priceinminutes',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
