# Generated by Django 3.1 on 2020-09-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200912_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinminutes',
            name='timestamp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
