# Generated by Django 3.1 on 2020-09-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200912_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinminutes',
            name='EUR',
        ),
        migrations.RemoveField(
            model_name='priceinminutes',
            name='GDP',
        ),
    ]
