# Generated by Django 3.1 on 2020-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200916_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinminutes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
