# Generated by Django 3.1 on 2020-09-13 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=15000.0, max_digits=20, null=True)),
                ('name', models.CharField(max_length=16, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bought', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('market_price_buy_usd', models.IntegerField(null=True)),
                ('market_price_buy_gbp', models.IntegerField(null=True)),
                ('market_price_buy_eur', models.IntegerField(null=True)),
                ('market_price_sell_usd', models.IntegerField(blank=True, null=True)),
                ('market_price_sell_gbp', models.IntegerField(blank=True, null=True)),
                ('market_price_sell_eur', models.IntegerField(blank=True, null=True)),
                ('amount_earned_btc', models.IntegerField(blank=True, null=True)),
                ('amount_earned_usd', models.IntegerField(blank=True, null=True)),
                ('amount_earned_gbp', models.IntegerField(blank=True, null=True)),
                ('amount_earned_eur', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
        ),
    ]
