# Generated by Django 3.1 on 2020-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='original_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
