# Generated by Django 3.1 on 2020-09-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200915_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_earned_eur',
            new_name='current_price_btc',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_earned_gbp',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_earned_usd',
        ),
    ]
