# Generated by Django 3.1 on 2020-09-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200915_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_bought',
            new_name='btc_bought',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_earned_btc',
            new_name='btc_earned',
        ),
    ]
