# Generated by Django 3.1 on 2020-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200915_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='current_price_btc',
            new_name='btc_buy_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_buy_eur',
            new_name='btc_sell_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_buy_gbp',
            new_name='eur_gained',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_buy_usd',
            new_name='eur_invested',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_sell_eur',
            new_name='gbp_gained',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_sell_gbp',
            new_name='gbp_invested',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_sell_usd',
            new_name='usd_gained',
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd_invested',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
