# Generated by Django 3.1 on 2020-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200915_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
