# Generated by Django 3.1 on 2020-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='btc_buy_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='btc_sell_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
