# Generated by Django 3.1 on 2020-09-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200912_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_earned_gdp',
            new_name='amount_earned_gbp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_buy_gdp',
            new_name='market_price_buy_gbp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='market_price_sell_gdp',
            new_name='market_price_sell_gbp',
        ),
    ]
