# Generated by Django 3.1 on 2020-09-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20200912_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
