# Generated by Django 3.1 on 2020-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20200912_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
