# Generated by Django 3.1 on 2020-09-13 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200912_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
