# Generated by Django 3.1 on 2020-09-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20200827_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
